### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by Tooconfident** [DebDebMN/prj-rev-bwfs-tea-cozy#2]
https://github.com/DebDebMN/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/index.html#L33-L50

Great job again with comments, especially on the closing tags. Also solid job properly tagging the id's on the anchor tags for navigation. This nav can be simpified just a bit using the [`<nav>` ](https://www.w3schools.com/tags/tag_nav.asp)html5 semantic element. [Semantic html5](https://www.w3schools.com/html/html5_semantic_elements.asp) elements like this were created to eliminate the need for too many div's. Also check out [`<footer>`](https://www.w3schools.com/html/html5_semantic_elements.asp) and [`<main>`](https://www.w3schools.com/tags/tag_main.asp)

https://gist.github.com/Tooconfident/a2e1812a91126e24ccfe73b1f9a8f307

**Comment by DebDebMN** [comment]
And I thought that they were "just" divs with good names :-)  Excellent suggestions. Will do!
