### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by Tooconfident** [DebDebMN/prj-rev-bwfs-tea-cozy#4]
https://github.com/DebDebMN/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L95

Not sure what you meant by weight here. Font-weight? or width? weight is an unknown property name. If you were looking for a width of 1200px, you can apply that to your main-container to maintain your boundaries and image positioning.

**Comment by DebDebMN** [comment]
Oooops!  Typo!  And thank you for your suggestion to move to main container.
